spring:
  application:
    name: demo

  datasource:
    url: jdbc:postgresql://database-1.cpy6ayaua0ly.ap-southeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: Haribol2026
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: health
