name: Java CI/CD with Docker

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-southeast-2
  ECR_REPOSITORY: harekrisna108nam-commits/demo
  CONTAINER_NAME: demo-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Application
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

      - name: SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          timeout: 60s
          command_timeout: 30m
          script: |
            set -e

            echo "Logging into ECR..."
            aws ecr get-login-password --region ap-southeast-2 | \
            docker login --username AWS --password-stdin \
            191537276755.dkr.ecr.ap-southeast-2.amazonaws.com

            echo "Pulling latest image..."
            docker pull \
            191537276755.dkr.ecr.ap-southeast-2.amazonaws.com/harekrisna108nam-commits/demo:latest

            echo "Stopping old container..."
            docker stop demo-app || true
            docker rm demo-app || true

            echo "Starting new container..."
            docker run -d \
              --restart unless-stopped \
              -p 80:8080 \
              --name demo-app \
              --label logging=promtail \
              191537276755.dkr.ecr.ap-southeast-2.amazonaws.com/harekrisna108nam-commits/demo:latest

            echo "Waiting for application startup..."
            sleep 30

            docker ps
            curl -f http://localhost:80/actuator/health || exit 1

            echo "Deployment Successful"